-- ============================================================================
-- Connector sync state — per-connector cursor + error bookkeeping
-- ============================================================================
--
-- A single generic table that any capture connector can use to remember where
-- it left off and whether its last run succeeded. Email importers, calendar
-- pollers, RSS readers, webhook receivers, backfill jobs — anything that pulls
-- from an external source on a schedule needs the same three things:
--
--   1. a cursor / high-watermark so the next run resumes instead of re-reading
--      everything from the start,
--   2. timestamps for when it last started, finished, and last succeeded, and
--   3. the last error (plus a running error count) so a stalled or failing
--      connector can be detected and alerted on.
--
-- This schema gives every connector one row to hold that state, keyed by the
-- connector's own identity — NOT by any thought. It never stores raw source
-- text; it is operational bookkeeping only.
--
-- Identity / key model:
--   The natural key is (connector, surface, sync_key):
--     connector — which connector this is, e.g. 'example_email'.
--     surface   — a named stream within that connector, e.g. 'inbox',
--                 'calendar:primary', 'webhook'. Use 'default' when a connector
--                 has only one stream.
--     sync_key  — the specific cursor scope within the surface, e.g. an account
--                 id, a folder, a label, or just 'default'.
--   A surfaced BIGINT `id` is the primary key so other operational tables can
--   reference a sync-state row cheaply, while the UNIQUE (connector, surface,
--   sync_key) constraint is what an upsert targets. There is no reference to
--   public.thoughts here and no thought id of any type — this table is keyed by
--   connector identity, so the canonical UUID thoughts.id never appears.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS, and
-- CREATE OR REPLACE FUNCTION. Additive only — it never alters or drops a column
-- on public.thoughts. No DELETE in this file. Safe to re-run.
-- ============================================================================

-- ─── Sync-state table ───────────────────────────────────────────────────────
-- One row per (connector, surface, sync_key). Holds the cursor and the
-- success/error state for that scope. `counters` and `metadata` are free-form
-- jsonb so a connector can stash run statistics (e.g. {"fetched": 42}) or
-- connector-specific config without a schema change.

CREATE TABLE IF NOT EXISTS public.connector_sync_state (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector        TEXT        NOT NULL,
  surface          TEXT        NOT NULL DEFAULT 'default',
  sync_key         TEXT        NOT NULL DEFAULT 'default',
  status           TEXT        NOT NULL DEFAULT 'pending',
  last_started_at  TIMESTAMPTZ,
  last_finished_at TIMESTAMPTZ,
  last_success_at  TIMESTAMPTZ,
  last_error_at    TIMESTAMPTZ,
  last_error       TEXT,
  error_count      INTEGER     NOT NULL DEFAULT 0,
  cursor_value     TEXT,
  high_watermark   TIMESTAMPTZ,
  counters         JSONB       NOT NULL DEFAULT '{}'::jsonb,
  metadata         JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (connector, surface, sync_key),
  CHECK (status IN ('pending', 'running', 'success', 'error'))
);

-- "Show me every surface for this connector, most recently touched first" —
-- the bread-and-butter dashboard query.
CREATE INDEX IF NOT EXISTS idx_connector_sync_state_connector_surface
  ON public.connector_sync_state (connector, surface, updated_at DESC);

-- "Which connectors are currently erroring (or stalled in 'running')?" — the
-- query a health monitor runs to raise alerts.
CREATE INDEX IF NOT EXISTS idx_connector_sync_state_status
  ON public.connector_sync_state (status, updated_at DESC);

-- Free-form metadata lookups (e.g. find every surface tagged a certain way).
CREATE INDEX IF NOT EXISTS idx_connector_sync_state_metadata_gin
  ON public.connector_sync_state USING gin (metadata);

ALTER TABLE public.connector_sync_state ENABLE ROW LEVEL SECURITY;

-- This is operational state for server-side connectors, not memory content.
-- Only the service role touches it. RLS denies everything else by default, and
-- we additionally revoke direct privileges from PUBLIC/anon/authenticated so a
-- Supabase project that blanket-grants new tables to its API roles cannot leave
-- this table exposed. Defense in depth: the explicit REVOKE makes the
-- service-role-only intent unambiguous regardless of project default privileges.
REVOKE ALL ON public.connector_sync_state FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.connector_sync_state TO service_role;

COMMENT ON TABLE public.connector_sync_state IS
  'Per-connector cursor + success/error bookkeeping. One row per (connector, surface, sync_key). Operational state only — no raw source text, no thought ids.';
COMMENT ON COLUMN public.connector_sync_state.connector IS
  'Connector identity, lowercase snake_case, e.g. example_email, example_calendar.';
COMMENT ON COLUMN public.connector_sync_state.surface IS
  'Named stream within the connector, e.g. inbox, calendar:primary. Use ''default'' for single-stream connectors.';
COMMENT ON COLUMN public.connector_sync_state.sync_key IS
  'Cursor scope within the surface, e.g. an account id or folder. Use ''default'' when there is only one.';
COMMENT ON COLUMN public.connector_sync_state.cursor_value IS
  'Opaque resume token for the source API (page token, history id, last seen id, etc.).';
COMMENT ON COLUMN public.connector_sync_state.high_watermark IS
  'Highest source timestamp processed so far. The next run can fetch only items newer than this.';

-- ─── Mark a run as started ──────────────────────────────────────────────────
-- Call at the top of a connector run. Creates the state row if it is the first
-- time this (connector, surface, sync_key) has run, otherwise stamps the start
-- and flips status to 'running'. Returns the row id.

CREATE OR REPLACE FUNCTION public.connector_sync_begin(
  p_connector TEXT,
  p_surface   TEXT DEFAULT 'default',
  p_sync_key  TEXT DEFAULT 'default'
) RETURNS BIGINT
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_id BIGINT;
BEGIN
  INSERT INTO public.connector_sync_state (connector, surface, sync_key, status, last_started_at, updated_at)
  VALUES (p_connector, p_surface, p_sync_key, 'running', now(), now())
  ON CONFLICT (connector, surface, sync_key) DO UPDATE
    SET status          = 'running',
        last_started_at = now(),
        updated_at      = now()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.connector_sync_begin(TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.connector_sync_begin(TEXT, TEXT, TEXT) TO service_role;

COMMENT ON FUNCTION public.connector_sync_begin IS
  'Mark a connector run as started: upsert the state row, set status=running and last_started_at. Returns the row id.';

-- ─── Record a successful run ────────────────────────────────────────────────
-- Call when a run finishes cleanly. Advances the cursor / high-watermark,
-- stamps success, resets the error count to 0, and clears the last error.
-- counters/metadata are merged (||) so a caller can update only the keys it
-- cares about; pass '{}'::jsonb to leave them unchanged.
--
-- No-regression guard: overlapping runs for the same (connector, surface,
-- sync_key) can finish out of order. Without a guard, an older run that
-- completes after a newer one would overwrite the newer cursor/high_watermark
-- with stale values. high_watermark is a TIMESTAMPTZ, so it is monotonic — we
-- only advance it when the incoming value is >= the stored one. cursor_value is
-- an opaque token (page tokens, history ids) that is not safely comparable on
-- its own, so we gate its advance on the same freshness signal: accept the
-- incoming cursor only when this completion is at least as fresh as the stored
-- high_watermark (or when there is nothing to compare against — no stored
-- watermark, or the caller does not supply one). The existing "only advance
-- when the caller supplies a new value" behaviour is preserved on top of this.

CREATE OR REPLACE FUNCTION public.connector_sync_success(
  p_connector      TEXT,
  p_surface        TEXT        DEFAULT 'default',
  p_sync_key       TEXT        DEFAULT 'default',
  p_cursor_value   TEXT        DEFAULT NULL,
  p_high_watermark TIMESTAMPTZ DEFAULT NULL,
  p_counters       JSONB       DEFAULT '{}'::jsonb
) RETURNS VOID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.connector_sync_state (
    connector, surface, sync_key, status,
    last_finished_at, last_success_at,
    cursor_value, high_watermark, error_count, last_error, counters, updated_at
  )
  VALUES (
    p_connector, p_surface, p_sync_key, 'success',
    now(), now(),
    p_cursor_value, p_high_watermark, 0, NULL, COALESCE(p_counters, '{}'::jsonb), now()
  )
  ON CONFLICT (connector, surface, sync_key) DO UPDATE
    SET status           = 'success',
        last_finished_at = now(),
        last_success_at  = now(),
        -- Advance the high_watermark only when the caller supplies a new one AND
        -- it is not older than the stored one (monotonic; never regress).
        high_watermark   = CASE
                             WHEN EXCLUDED.high_watermark IS NULL
                               THEN public.connector_sync_state.high_watermark
                             WHEN public.connector_sync_state.high_watermark IS NULL
                               THEN EXCLUDED.high_watermark
                             WHEN EXCLUDED.high_watermark >= public.connector_sync_state.high_watermark
                               THEN EXCLUDED.high_watermark
                             ELSE public.connector_sync_state.high_watermark
                           END,
        -- Advance the cursor only when the caller supplies one AND this
        -- completion is at least as fresh as the stored high_watermark. The
        -- cursor is opaque, so the watermark is the freshness signal; if there
        -- is nothing to compare against (no stored or no incoming watermark),
        -- fall back to the prior "advance when supplied" behaviour.
        cursor_value     = CASE
                             WHEN EXCLUDED.cursor_value IS NULL
                               THEN public.connector_sync_state.cursor_value
                             WHEN EXCLUDED.high_watermark IS NULL
                               OR public.connector_sync_state.high_watermark IS NULL
                               OR EXCLUDED.high_watermark >= public.connector_sync_state.high_watermark
                               THEN EXCLUDED.cursor_value
                             ELSE public.connector_sync_state.cursor_value
                           END,
        error_count      = 0,
        last_error       = NULL,
        counters         = public.connector_sync_state.counters || COALESCE(p_counters, '{}'::jsonb),
        updated_at       = now();
END;
$$;

REVOKE ALL ON FUNCTION public.connector_sync_success(TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.connector_sync_success(TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ, JSONB) TO service_role;

COMMENT ON FUNCTION public.connector_sync_success IS
  'Record a clean run: advance cursor/high_watermark (no-regression guard — never moves them backward when an older overlapping run finishes late), stamp success, reset error_count, clear last_error, merge counters.';

-- ─── Record a failed run ────────────────────────────────────────────────────
-- Call when a run errors out. Stamps the error, increments error_count, and
-- leaves the cursor / high-watermark untouched so the next run retries from the
-- last known-good position rather than skipping the failed window.

CREATE OR REPLACE FUNCTION public.connector_sync_error(
  p_connector TEXT,
  p_surface   TEXT DEFAULT 'default',
  p_sync_key  TEXT DEFAULT 'default',
  p_error     TEXT DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.connector_sync_state (
    connector, surface, sync_key, status,
    last_finished_at, last_error_at, last_error, error_count, updated_at
  )
  VALUES (
    p_connector, p_surface, p_sync_key, 'error',
    now(), now(), p_error, 1, now()
  )
  ON CONFLICT (connector, surface, sync_key) DO UPDATE
    SET status           = 'error',
        last_finished_at = now(),
        last_error_at    = now(),
        last_error       = p_error,
        error_count      = public.connector_sync_state.error_count + 1,
        updated_at       = now();
END;
$$;

REVOKE ALL ON FUNCTION public.connector_sync_error(TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.connector_sync_error(TEXT, TEXT, TEXT, TEXT) TO service_role;

COMMENT ON FUNCTION public.connector_sync_error IS
  'Record a failed run: stamp last_error_at/last_error, increment error_count, leave cursor/high_watermark untouched for retry.';

-- Make the new table and RPCs visible to PostgREST immediately.
NOTIFY pgrst, 'reload schema';
